### ISSUE TITLE
Generating wall.

### ISSUE THREAD

**Issue by jieliangang** [cs3217-dash/dash#6]
- Create top and bottom boundaries of the game which is logical, and progressively gets tougher.

**Comment by jo-lyn** [comment]
http://www.gamasutra.com/blogs/AdamSaltsman/20100929/6096/

http://www.gamasutra.com/view/feature/170049/how_to_make_insane_procedural_.php

https://www.bitshiftprogrammer.com/2018/01/altos-adventure-style-procedural.html

https://www.raywenderlich.com/2637-procedural-level-generation-in-games-tutorial-part-1

https://www.hackingwithswift.com/example-code/games/how-to-create-a-random-terrain-tile-map-using-sktilemapnode-and-gkperlinnoisesource

https://medium.com/@nickcracchiolo/procedural-tile-maps-with-sprite-kit-a07d8f062ec4

https://stackoverflow.com/questions/44892419/generating-random-terrain-in-spritekit

https://www.gamasutra.com/view/news/335241/Road_to_the_IGF_Team_Altos_Altos_Odyssey.php
